# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 366e24c83336b6859609d26e167aad50f263db627f8a3843f70497ba9d62ad6d929a2e2c27b6d600cb6d2d8af568f40f87ddc26d807467c04665173c1767d70b

test:
  secret_key_base: 11cd8bcbe2c27ad5b259999c19f006bd041ed6e173751a6b8168900979d545e59c64d50d3a573d311ef7b7564b8a663dc890b047eb3ff5031e95b54fd17ccfc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
